version = 4.1.1
archive_dir = /etc/letsencrypt/archive/dev.muttivillas.com
cert = /etc/letsencrypt/live/dev.muttivillas.com/cert.pem
privkey = /etc/letsencrypt/live/dev.muttivillas.com/privkey.pem
chain = /etc/letsencrypt/live/dev.muttivillas.com/chain.pem
fullchain = /etc/letsencrypt/live/dev.muttivillas.com/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 7bd2fd185262cf236f56f774ee3194c8
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
dev.muttivillas.com = /var/www/html
