version = 4.2.0
archive_dir = /etc/letsencrypt/archive/dev2.muttivillas.ru
cert = /etc/letsencrypt/live/dev2.muttivillas.ru/cert.pem
privkey = /etc/letsencrypt/live/dev2.muttivillas.ru/privkey.pem
chain = /etc/letsencrypt/live/dev2.muttivillas.ru/chain.pem
fullchain = /etc/letsencrypt/live/dev2.muttivillas.ru/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 8dfc8a34099de49e8b46e4c04e3f6cc3
authenticator = webroot
webroot_path = /var/www/html,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
dev2.muttivillas.ru = /var/www/html
