services:
  php:
    build:
      context: ./php
    image: php8.4.8-fpm
    container_name: ${PROJECT_NAME}_php8.4.8-fpm
    restart: always
    expose:
      - "9000"  # Порт для PHP-FPM, теперь напрямую используется Nginx
    volumes:
      - ./app:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env

  nginx:
    image: nginx:1.27.5
    container_name: ${PROJECT_NAME}_nginx
    restart: always
    ports:
      - "${LOCALHOST_PORT}:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./app:/var/www/html  # Прямая монтировка кода Bitrix
    depends_on:
      - php  # Теперь зависит только от PHP-FPM
    networks:
      - ${DOCKER_NETWORK}

  db:
    image: mysql:8.4.5
    container_name: ${PROJECT_NAME}_mysql8.4
    restart: always
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mutti.sql:/docker-entrypoint-initdb.d/mutti.sql
      - ${VOLUME_DB_DATA}:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env

  redis:
    image: redis:8.2-m01-alpine3.22
    container_name: ${PROJECT_NAME}_redis8.2
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ${VOLUME_REDIS_DATA}:/data
      - ./app:/var/www/html
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - ${DOCKER_NETWORK}
    
  node:
    image: node:22-slim
    container_name: bitrix_node22
    restart: always
    working_dir: /var/www/html/frontend/
    user: www-data
    volumes:
      - ./app:/var/www/html/
    ports:
      - "3000:3000"
    command: [ "sh", "-c", "npm install && npm run build" ]
    networks:
      - ${DOCKER_NETWORK}
    env_file:
      - .env
    depends_on:
      - db
      - redis

networks:
  docker-network:
    external: true

volumes:
  db_bitrix:
  db_redis:
