worker_processes auto;
error_log /var/log/nginx/error.log;
pid       /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 200M;
	
	add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

	
    # GZIP
    gzip on;
    gzip_types
        text/plain
        text/css
        text/xml
        text/javascript
        application/json
        application/javascript
        application/xml+rss
        application/atom+xml
        image/svg+xml;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 7;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;

    include /etc/nginx/conf.d/*.conf;
}
