worker_processes auto;
error_log /var/log/nginx/error.log;
pid       /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    client_max_body_size 200M;

    # GZIP
    gzip on;
    gzip_types text/plain text/css application/javascript text/xml application/xml image/svg+xml;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_buffers 16 8k;
    gzip_http_version 1.1;

    include /etc/nginx/conf.d/*.conf;
}
