server {
    listen 443 ssl;
    server_name dev.muttivillas.com;
    root /var/www/html;

    #внимательно, эти пути сертификатов это пути в контейнере
	ssl_certificate     /etc/nginx/ssl/live/dev.muttivillas.com/fullchain.pem;
	ssl_certificate_key /etc/nginx/ssl/live/dev.muttivillas.com/privkey.pem;

    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # certbot-challenge (можно оставить на всякий случай)
    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        try_files $uri =404;
        allow all;
    }

    # статика
	location ~* \.(css|js|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot|pdf|zip|webp|mp4|mov|avi|json)$ {
		root /var/www/html;
		try_files $uri =404;
		expires 30d;
		add_header Cache-Control "public, immutable";
		access_log off;
	}

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_read_timeout 180;
    }

    # ЧПУ
    location / {
        index index.php index.html;
        try_files $uri $uri/ /index.php?$args;
    }

    # запрет скрытых файлов
    location ~ /\. {
        deny all;
        access_log off;
        log_not_found off;
    }
}
