server {
    listen 80;
    server_name dev2.muttivillas.ru;
    root /var/www/html;

    # для certbot
    location ^~ /.well-known/acme-challenge/ {
        default_type "text/plain";
        try_files $uri =404;
        allow all;
    }

    # редирект всего остального на HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}
